---
- hosts: localhost
  gather_facts: false
  vars:
    cluster_name: foo
    nios_config:
      infoblox_host: rho-dns-a.rho.lab.signal9.gg
      metallb_network_container: 172.18.72.0/21
  tasks:
  - name: fetch existing networks
    ansible.builtin.set_fact:
      metallb_network: "{{ lookup('infoblox.nios_modules.nios_lookup', 'network', provider={'host': nios_config.infoblox_host}, filter={'comment': cluster_name}) }}"
      next_network: "{{ lookup('infoblox.nios_modules.nios_next_network', nios_config.metallb_network_container, cidr=25, provider={'host': nios_config.infoblox_host}) }}"
  
  - name: debug existing network
    ansible.builtin.debug:
      msg: "{{ metallb_network }} Next: {{ next_network }}"

  - name: allocate new network
    infoblox.nios_modules.nios_network:
      comment: "{{ cluster_name }}"
      provider:
        host: "{{ nios_config.infoblox_host }}"
      network: "{{ next_network | first }}"
      state: present
    when: metallb_network | length == 0

  - name: fetch existing networks
    ansible.builtin.set_fact:
      metallb_network: "{{ lookup('infoblox.nios_modules.nios_lookup', 'network', provider={'host': nios_config.infoblox_host }, filter={'comment': cluster_name}) }}"
  
  - name: debug existing network
    ansible.builtin.debug:
      msg: "{{ metallb_network }}"

  - name: deallocate network
    infoblox.nios_modules.nios_network:
      provider:
        host: "{{ nios_config.infoblox_host }}"
      network: "{{ metallb_network.network }}"
      state: absent
    when: metallb_network | length > 0

