apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: xf-1.rho.lab.signal9.gg
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-options: 'ServerSideApply=True'
spec:
  bootMode: legacy
  bootMACAddress: '00:02:c9:2f:30:c0'
  online: true
  bmc:
    address: 'ilo4-virtualmedia://ilo-hp-blade-1.oob.signal9.gg'
    credentialsName: "xf-1"
    disableCertificateVerification: true
