apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: xf-2.rho.lab.signal9.gg
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=True"
spec:
  bootMode: legacy
  bootMACAddress: '00:02:c9:2f:4d:80'
  online: true
  bmc:
    address: 'ilo4-virtualmedia://ilo-hp-blade-2.oob.signal9.gg'
    credentialsName: 'xf-2'
    disableCertificateVerification: true
