apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-helm
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://gitea.apps.xna-foundation.rho.lab.signal9.gg/mirror/vault-helm.git'
    targetRevision: v0.27.0
    path: '.'
    helm:
      values: |
        global:
          openshift: true
          tlsDisable: true
        injector:
          image:
            repository: "bastion.rho.lab.signal9.gg:8443/mirror/hashicorp/vault-k8s"
            tag: "1.3.1-ubi"
        
          agentImage:
            repository: "bastion.rho.lab.signal9.gg:8443/mirror/hashicorp/vault"
            tag: "1.15.2-ubi"
        
        server:
          route:
            enabled: true
            tls:
              termination: edge
            host: vault.apps.xna-foundation.rho.lab.signal9.gg

          image:
            repository: "bastion.rho.lab.signal9.gg:8443/mirror/hashicorp/vault"
            tag: "1.15.2-ubi"

          readinessProbe:
            path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"

          podDisruptionBudget:
            maxUnavailable: 2
     
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
              config: |
                ui = true
                listener "tcp" {
                  tls_disable = 1
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                  # Enable unauthenticated metrics access (necessary for Prometheus Operator)
                  telemetry {
                    unauthenticated_metrics_access = "true"
                  }
                }
                storage "raft" {
                  path = "/vault/data"
                  retry_join {
                    leader_api_addr = "http://vault-helm-0.vault-helm-internal:8200"
                  }

                }
                service_registration "kubernetes" {}            
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  syncPolicy:
    automated: {}
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
