apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shared-openid-secret
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: hcp-oauth-client-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: hcp-shared-openid
