apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baremetal-manager
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    automated:
      prune: true
  ignoreDifferences:
    - group: metal3.io
      kind: BareMetalHost
      jsonPointers:
        - /spec/online
        - /spec/networkData
        - /spec/metaData
        - /spec/image
  project: default
  source:
    repoURL: 'https://gitea.apps.xna-foundation.rho.lab.signal9.gg/rho-lab/gitops.git'
    targetRevision: HEAD
    path: 'charts/metal-node-assignment'
    helm:
      values: |
        nodes:
        - name: xf-10.rho.lab.signal9.gg
          deployed: true
          namespace: openshift-machine-api
          labels:
            compute-model: sl230
          bootMac: 2c:41:38:eb:da:18
          bmc:
            url: ipmi://ilo-hp-blade-4.oob.signal9.gg
            externalSecret:
              vaultName: openshift-signal9-ldap
              usernameKey: username
              passwordKey: ipmi_password
          network:
            dnsServers:
              - 172.18.60.10
            bond0Interfaces:
              - eno1
              - eno2
            bond1Interfaces:
              - eno3
              - eno3d1
            mgmtGateway: 172.18.63.1
            odfGateway: 172.18.66.1
            mgmtVlan: 603
            odfVlan: 606
            mgmtIp: 172.18.63.10
            odfIp: 172.18.66.10
        - name: xf-11.rho.lab.signal9.gg
          deployed: true
          namespace: openshift-machine-api
          labels:
            compute-model: sl230
          bootMac: 2c:41:38:eb:d2:64
          bmc:
            url: ipmi://ilo-hp-blade-5.oob.signal9.gg
            externalSecret:
              vaultName: openshift-signal9-ldap
              usernameKey: username
              passwordKey: ipmi_password
          network:
            dnsServers:
              - 172.18.60.10
            bond0Interfaces:
              - eno1
              - eno2
            bond1Interfaces:
              - eno3
              - eno3d1
            mgmtGateway: 172.18.63.1
            odfGateway: 172.18.66.1
            mgmtVlan: 603
            odfVlan: 606
            mgmtIp: 172.18.63.11
            odfIp: 172.18.66.11
        - name: xf-12.rho.lab.signal9.gg
          deployed: true
          namespace: openshift-machine-api
          labels:
            compute-model: sl230
          bootMac: 2c:41:38:eb:d3:90
          bmc:
            url: ipmi://ilo-hp-blade-6.oob.signal9.gg
            externalSecret:
              vaultName: openshift-signal9-ldap
              usernameKey: username
              passwordKey: ipmi_password
          network:
            dnsServers:
              - 172.18.60.10
            bond0Interfaces:
              - eno1
              - eno2
            bond1Interfaces:
              - eno3
              - eno3d1
            mgmtGateway: 172.18.63.1
            odfGateway: 172.18.66.1
            mgmtVlan: 603
            odfVlan: 606
            mgmtIp: 172.18.63.12
            odfIp: 172.18.66.12
        - name: xf-13.rho.lab.signal9.gg
          deployed: true
          namespace: openshift-machine-api
          labels:
            compute-model: sl230
          bootMac: e8:39:35:f0:32:2c
          bmc:
            url: ipmi://ilo-hp-blade-7.oob.signal9.gg
            externalSecret:
              vaultName: openshift-signal9-ldap
              usernameKey: username
              passwordKey: ipmi_password
          network:
            dnsServers:
              - 172.18.60.10
            bond0Interfaces:
              - eno1
              - eno2
            bond1Interfaces:
              - eno3
              - eno3d1
            mgmtGateway: 172.18.63.1
            odfGateway: 172.18.66.1
            mgmtVlan: 603
            odfVlan: 606
            mgmtIp: 172.18.63.13
            odfIp: 172.18.66.13
        - name: xf-14.rho.lab.signal9.gg
          deployed: true
          namespace: openshift-machine-api
          labels:
            compute-model: sl230
          bootMac: 2c:41:38:eb:d3:2c
          bmc:
            url: ipmi://ilo-hp-blade-8.oob.signal9.gg
            externalSecret:
              vaultName: openshift-signal9-ldap
              usernameKey: username
              passwordKey: ipmi_password
          network:
            dnsServers:
              - 172.18.60.10
            bond0Interfaces:
              - eno1
              - eno2
            bond1Interfaces:
              - eno3
              - eno3d1
            mgmtGateway: 172.18.63.1
            odfGateway: 172.18.66.1
            mgmtVlan: 603
            odfVlan: 606
            mgmtIp: 172.18.63.14
            odfIp: 172.18.66.14
        - name: xf-15.rho.lab.signal9.gg
          deployed: true
          namespace: openshift-machine-api
          labels:
            compute-model: smc
          bootMac: 00:25:90:85:1f:02
          bmc:
            url: ipmi://bmc-smc-node1.oob.signal9.gg
            externalSecret:
              vaultName: openshift-signal9-ldap
              usernameKey: smc_username
              passwordKey: smc_password
          network:
            dnsServers:
              - 172.18.60.10
            bond0Interfaces:
              - eno1
              - eno2
            bond1Interfaces:
              - enp131s0f0
              - enp131s0f1
            mgmtGateway: 172.18.63.1
            odfGateway: 172.18.66.1
            mgmtVlan: 603
            odfVlan: 606
            mgmtIp: 172.18.63.15
            odfIp: 172.18.66.15
        - name: xf-16.rho.lab.signal9.gg
          deployed: true
          namespace: openshift-machine-api
          labels:
            compute-model: smc
          bootMac: 00:25:90:85:20:36
          bmc:
            url: ipmi://bmc-smc-node-2.oob.signal9.gg
            externalSecret:
              vaultName: openshift-signal9-ldap
              usernameKey: smc_username
              passwordKey: smc_password
          network:
            dnsServers:
              - 172.18.60.10
            bond0Interfaces:
              - eno1
              - eno2
            bond1Interfaces:
              - enp131s0f0
              - enp131s0f1
            mgmtGateway: 172.18.63.1
            odfGateway: 172.18.66.1
            mgmtVlan: 603
            odfVlan: 606
            mgmtIp: 172.18.63.16
            odfIp: 172.18.66.16
        - name: xf-17.rho.lab.signal9.gg
          deployed: true
          namespace: test-infraenv
          annotations:
            inspect.metal3.io: disabled
          labels:
            compute-model: smc
            infraenvs.agent-install.openshift.io: test-infraenv
          bootMac: 00:25:90:85:75:7c
          bmc:
            url: ipmi://bmc-smc-node-3.oob.signal9.gg
            externalSecret:
              vaultName: openshift-signal9-ldap
              usernameKey: smc_username
              passwordKey: smc_password
          network:
            dnsServers:
              - 172.18.60.10
            bond0Interfaces:
              - eno1
              - eno2
            bond1Interfaces:
              - enp131s0f0
              - enp131s0f1
            mgmtGateway: 172.18.63.1
            odfGateway: 172.18.66.1
            mgmtVlan: 603
            odfVlan: 606
            mgmtIp: 172.18.63.17
            odfIp: 172.18.66.17
        - name: xf-18.rho.lab.signal9.gg
          deployed: true
          namespace: openshift-machine-api
          labels:
            compute-model: r720
          bootMac: b8:ca:3a:62:95:a4
          bmc:
            url: ipmi://r720-1-drac.oob.signal9.gg
            externalSecret:
              vaultName: openshift-signal9-ldap
              usernameKey: username
              passwordKey: ipmi_password
          network:
            dnsServers:
              - 172.18.60.10
            bond0Interfaces:
              - eno3
              - eno4
            bond1Interfaces:
              - enp65s0
              - enp65s0d1
            mgmtGateway: 172.18.63.1
            odfGateway: 172.18.66.1
            mgmtVlan: 603
            odfVlan: 606
            mgmtIp: 172.18.63.18
            odfIp: 172.18.66.18
        - name: xf-19.rho.lab.signal9.gg
          deployed: true
          namespace: openshift-machine-api
          labels:
            compute-model: r720
          bootMac: bc:30:5b:f1:d7:14
          bmc:
            url: ipmi://r720-2-drac.oob.signal9.gg
            externalSecret:
              vaultName: openshift-signal9-ldap
              usernameKey: username
              passwordKey: ipmi_password
          network:
            dnsServers:
              - 172.18.60.10
            bond0Interfaces:
              - eno3
              - eno4
            bond1Interfaces:
              - enp65s0
              - enp65s0d1
            mgmtGateway: 172.18.63.1
            odfGateway: 172.18.66.1
            mgmtVlan: 603
            odfVlan: 606
            mgmtIp: 172.18.63.19
            odfIp: 172.18.66.19
        - name: xf-20.rho.lab.signal9.gg
          deployed: true
          namespace: openshift-machine-api
          labels:
            compute-model: r720
          bootMac: 18:66:da:ea:27:ee
          bmc:
            url: ipmi://r720-3-drac.oob.signal9.gg
            externalSecret:
              vaultName: openshift-signal9-ldap
              usernameKey: username
              passwordKey: ipmi_password
          network:
            dnsServers:
              - 172.18.60.10
            bond0Interfaces:
              - eno3
              - eno4
            bond1Interfaces:
              - enp65s0
              - enp65s0d1
            mgmtGateway: 172.18.63.1
            odfGateway: 172.18.66.1
            mgmtVlan: 603
            odfVlan: 606
            mgmtIp: 172.18.63.20
            odfIp: 172.18.66.20

