apiVersion: v1 
kind: Secret
metadata:
 name: smc-net-config
 namespace: openshift-machine-api
type: Opaque
stringData:
 nmstate: | 
   interfaces:
     - name: bond0
       type: bond
       state: up
       ipv4:
         enabled: false
         dhcp: false
       ipv6:
         enabled: false
       link-aggregation:
         mode: active-backup
         options:
           miimon: '100'
         port:
           - eno1
           - eno2
     - name: provisioning
       type: vlan
       state: up
       mtu: 1500
       vlan:
         id: 602
         base-iface: bond0
       ipv4:
         enabled: true
         dhcp: true
     - name: bond1
       type: bond
       mtu: 9000
       state: up
       ipv4:
         enabled: false
         dhcp: false
       ipv6:
         enabled: false
       link-aggregation:
         mode: active-backup
         options:
           miimon: '100'
         port:
           - enp131s0f0
           - enp131s0f1
     - name: rho-ocp
       type: vlan
       state: up
       mtu: 9000
       vlan:
         id: 603
         base-iface: bond1
       ipv4:
         enabled: true
         dhcp: true
   dns-resolver:
     config:
       server:
         - 172.18.60.10
