---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitea-scc-clusterrole
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  - nonroot-v2
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitea-scc-binding
  namespace: gitea
subjects:
  - kind: ServiceAccount
    namespace: gitea
    name: gitea
  - kind: ServiceAccount
    namespace: gitea
    name: gitea-postgresql-ha
  - kind: ServiceAccount
    namespace: gitea
    name: gitea-redis-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitea-scc-clusterrole
---
