kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: gitea
  namespace: gitea
spec:
  host: gitea.apps.xna-foundation.rho.lab.signal9.gg
  to:
    kind: Service
    name: gitea-http
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
