---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: internalapi
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "internalapi",
      "type": "macvlan",
      "master": "osp-int-api",
      "ipam": {
        "type": "whereabouts",
        "range": "172.18.64.0/24",
        "range_start": "172.18.64.30",
        "range_end": "172.18.64.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: public
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "public",
      "type": "macvlan",
      "master": "osp-pub",
      "ipam": {
        "type": "whereabouts",
        "range": "172.18.67.0/24",
        "range_start": "172.18.67.30",
        "range_end": "172.18.67.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: tunnel
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "tunnel",
      "type": "macvlan",
      "master": "osp-tun",
      "ipam": {
        "type": "whereabouts",
        "range": "172.18.65.0/24",
        "range_start": "172.18.65.30",
        "range_end": "172.18.65.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: storage
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "storage",
      "type": "macvlan",
      "master": "odf",
      "ipam": {
        "type": "whereabouts",
        "range": "172.18.66.0/24",
        "range_start": "172.18.66.200",
        "range_end": "172.18.66.230",
        "routes": [
          {
            "dst": "172.18.14.0/24",
            "gw": "172.18.66.1"
          }
        ]
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ctlplane
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "internalapi",
      "type": "macvlan",
      "master": "provisioning",
      "ipam": {
        "type": "whereabouts",
        "range": "172.18.62.0/24",
        "range_start": "172.18.62.201",
        "range_end": "172.18.62.230"
      }
    }

