apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-kubevirt3-deploy
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: "https://kubernetes.default.svc"
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - RespectIgnoreDifferences=true
  source:
    repoURL: "https://gitea.apps.xna-foundation.rho.lab.signal9.gg/rho-lab/gitops.git"
    path: "charts/hcp-cluster-build"
    targetRevision: HEAD
    helm:
      valueFiles:
        - "../../argocd/clusters/workload-clusters/test-kubevirt3/helm-values/build-values.yaml"
