# expected to be kubevirt or agent
platform: kubevirt

cluster:
  name: test-kubevirt8
  baseDomain: rho.lab.signal9.gg
  foundationIngressBaseDomain: apps.xna-foundation.rho.lab.signal9.gg

rbac:
  globalAdminGroups:
    - global-admins

ingress:
  managed: true
