- hosts: localhost
  gather_facts: false
  vars:
    cluster_state: present
  tasks:
    - name: set ingress_base_domain
      ansible.builtin.set_face:
        ingress_base_domain: "{{ platform_configs[cluster_platform].ingress_base_domain }}"

    - name: include resource_allocation role
      ansible.builtin.include_role:
        name: resource_allocation

    - name: include dns role
      ansible.builtin.include_role:
        name: dns_config

    - name: include sso_client role
      ansible.builtin.include_role:
        name: sso_client

    - name: include gitops_cluster_build role
      ansible.builtin.include_role:
        name: gitops_cluster_build

    - name: include vault_config role
      ansible.builtin.include_role:
        name: vault_config
