apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: infoblox-credentials
  namespace: external-dns-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: infoblox-credentials
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        EXTERNAL_DNS_INFOBLOX_WAPI_USERNAME: "{{ .username }}"
        EXTERNAL_DNS_INFOBLOX_WAPI_PASSWORD: "{{ .password }}"
  data:
  - secretKey: username
    remoteRef:
      key: infoblox-creds
      property: username
  - secretKey: password
    remoteRef:
      key: infoblox-creds
      property: password
