apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
  annotations:
    argocd.argoproj.io/sync-wave: '3'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  mirrorRegistryRef:
    name: custom-registries
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  osImages: 
    - openshiftVersion: "4.14"
      cpuArchitecture: x86_64
      url: http://bastion.rho.lab.signal9.gg/rhcos-4.14.0-ec.2-x86_64-live.x86_64.iso
      version: "414.92.202305090606-0"
