apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-registries
  namespace: multicluster-engine
  labels:
    app: assisted-service
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIID9DCCAtygAwIBAgIUChDVXSavo+UD/TL6UsPTWSu5Vu4wDQYJKoZIhvcNAQEL
    BQAwdDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
    azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xIzAhBgNVBAMMGmJh
    c3Rpb24ucmhvLmxhYi5zaWduYWw5LmdnMB4XDTI0MDExMTE0MTk1N1oXDTI2MTAz
    MTE0MTk1N1owdDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhO
    ZXcgWW9yazENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xIzAhBgNV
    BAMMGmJhc3Rpb24ucmhvLmxhYi5zaWduYWw5LmdnMIIBIjANBgkqhkiG9w0BAQEF
    AAOCAQ8AMIIBCgKCAQEAtbEWekWUIy40El+dZJAk8t652T3rcNpx8wIpq9+K1zJP
    I06//8sQkHBRYubG28+ahT3HvqGw4zLiuv00EX2aKYPMrhwlpkHsrhqRJ5FWP/Wz
    Ydy94FakyviFHRkLFNwg8fIH8xxqZPuoQlzCLMycuE2IA70299BNaFwEcTogOkgo
    hqA6zuWFI2Zv/FUPbfhjm8aHiZmaAhpk5Zut2504CuYvWixi4xC5ZTW2fO+hOD34
    Ipc+1SJgOREMDNzI9ix7oAZLmp30ouiAqOg3cVVecdTOF/NZLyfiprmHp2MJx/Yb
    i4Q92v6b3DiuHjU6QP/tFPxN7jpJlYlAWl4NzT6UZwIDAQABo34wfDALBgNVHQ8E
    BAMCAuQwEwYDVR0lBAwwCgYIKwYBBQUHAwEwJQYDVR0RBB4wHIIaYmFzdGlvbi5y
    aG8ubGFiLnNpZ25hbDkuZ2cwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQU
    ucTcFhHDOVqO5kKCDvXQzvPNwEkwDQYJKoZIhvcNAQELBQADggEBAKyoNoxSQI2Q
    VtdVueW0BI8XuM0TsV5NCAKlUy7KTVOQzCJcP5q41POTgz6M7RZ0f1kf0Y3uslZB
    yNAI/4xpI3ImuOeG8OT04qDT/v27qNbjqZaaDCz1iGDVAR1Y7dIFMe4KanUr56GM
    YN0Db+jT0UGOWINV1KqZJxZmowIt7WztBSU6BP1s7bUgTql6QzFNn7VzjynAWESe
    Jr/fRwT3LFmHirg5rg/QpZFs5/PF5OR/VSe+lu5SBJOlLWr5Ykb08ccY688oVtM9
    Bm7SEbJue9ZvwVsQWlSPiZbk08pjKTQeolQCVYNWMUdfZAu8RYDp8XsCPEE6sdW6
    JWS084L9hgk=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIICkTCCAhagAwIBAgIUX1Cm8VWt4ki4+8XH7oKsYYKJM+QwCgYIKoZIzj0EAwIw
    dzELMAkGA1UEBhMCVVMxETAPBgNVBAgMCEFya2Fuc2FzMQ8wDQYDVQQHDAZSb2dl
    cnMxFTATBgNVBAoMDFNpZ25hbDkgTGFiczEMMAoGA1UECwwDWE5BMR8wHQYDVQQD
    DBZTaWduYWw5IFJvb3QgQXV0aG9yaXR5MB4XDTIxMDMwMTA0MDMwNFoXDTQxMDIy
    NDA0MDMwNFowdzELMAkGA1UEBhMCVVMxETAPBgNVBAgMCEFya2Fuc2FzMQ8wDQYD
    VQQHDAZSb2dlcnMxFTATBgNVBAoMDFNpZ25hbDkgTGFiczEMMAoGA1UECwwDWE5B
    MR8wHQYDVQQDDBZTaWduYWw5IFJvb3QgQXV0aG9yaXR5MHYwEAYHKoZIzj0CAQYF
    K4EEACIDYgAE5w5BHLiaagf5eSNkQYuDIdyWe7ULLY2z2qAP1fKXM+RrSHQQb5x1
    Q9+IhQRhf7exw/pJS5Vs1R8IyQ3B8r6xz885w6+Fk6iyMAlFn979RU6V5lbxMRGG
    Vxq/CEL/iorVo2MwYTAdBgNVHQ4EFgQUYfO+q+KnTtIDK5OFXsVZ/D0ziiUwHwYD
    VR0jBBgwFoAUYfO+q+KnTtIDK5OFXsVZ/D0ziiUwDwYDVR0TAQH/BAUwAwEB/zAO
    BgNVHQ8BAf8EBAMCAYYwCgYIKoZIzj0EAwIDaQAwZgIxAJLOIPP9J1/mttvGdQtM
    Prnm+r+JzVu8vd0r2HxgwloEkElTr29S+DAAE8XlUpoXpQIxALEd+sYGr1qENJqr
    vHOvuo0diFSUxjvTjowus6kM6nZi1JR4rMycICsGgujg8zwVAw==
    -----END CERTIFICATE-----
  registries.conf: |
    unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/openshift4"
    mirror-by-digest-only = true

    [[registry.mirror]]
    location = "bastion.rho.lab.signal9.gg:8443/mirror/openshift4"

    [[registry]]
    prefix = ""
    location = "quay.io/openshift-release-dev/ocp-release"
    mirror-by-digest-only = true

    [[registry.mirror]]
    location = "bastion.rho.lab.signal9.gg:8443/mirror/openshift/release-images"

    [[registry]]
    prefix = ""
    location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
    mirror-by-digest-only = true

    [[registry.mirror]]
    location = "bastion.rho.lab.signal9.gg:8443/mirror/openshift/release"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/rhacm2"
    mirror-by-digest-only = true

    [[registry.mirror]]
    location = "bastion.rho.lab.signal9.gg:8443/mirror/rhacm2"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/multicluster-engine"
    mirror-by-digest-only = true

    [[registry.mirror]]
    location = "bastion.rho.lab.signal9.gg:8443/mirror/multicluster-engine"

