apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: signal9
  namespace: quay
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  configBundleSecret: signal9-quay-config
  components:
    - managed: true
      kind: clair
    - managed: true
      kind: postgres
    - managed: false
      kind: objectstorage
    - managed: true
      kind: redis
    - managed: true
      kind: horizontalpodautoscaler
    - managed: false
      kind: route
    - managed: true
      kind: mirror
    - managed: true
      kind: monitoring
    - managed: false
      kind: tls
    - managed: true
      kind: quay
    - managed: true
      kind: clairpostgres
