apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: signal9-quay-config
  namespace: quay
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: signal9-quay-config
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: quay-config
