# High-level variables used in cluster provisioning

# DNS domain where all managed OCP clusters will be created
base_domain: "rho.lab.signal9.gg"
gitops_repo_url: "https://gitea.apps.xna-foundation.rho.lab.signal9.gg/rho-lab/gitops.git"
gitops_repo_url_authed: "https://{{ upstream_git_user|urlencode }}:{{ upstream_git_password|urlencode }}@gitea.apps.xna-foundation.rho.lab.signal9.gg/rho-lab/gitops.git"
cluster_builds_dir: "argocd/clusters/xna-foundation/live/cluster-builds"

hashicorp_vault:
  url: "https://vault.apps.xna-foundation.rho.lab.signal9.gg"
  auth_type: jwt
  auth_mount: k8s-xna-foundation
  jwt_location: "/var/run/secrets/kubernetes.io/serviceaccount/token"
  auth_role: rho-aap
  # Policy to be used for new k8s auth methods
  cluster_policy: "rho-k8s-default"
  # Name for new k8s auth method
  vault_managed_auth_name: "k8s-mgd-{{ cluster_name }}"
  secret_base_path: lab
  # Vault secrets to be referenced when generating cluster configurations
  cluster_secrets:
    oidc: "{{ cluster_name }}-openid"
    pull_secret: ocp-pull-secret

# CA bundle to be added to provisioned clusters, may not match platform
# bundle. Should include the root CA for the OCP API even if it is normally
# public for Vault configuration.
cluster_trust_bundle: |
  -----BEGIN CERTIFICATE-----
  MIICkTCCAhagAwIBAgIUX1Cm8VWt4ki4+8XH7oKsYYKJM+QwCgYIKoZIzj0EAwIw
  dzELMAkGA1UEBhMCVVMxETAPBgNVBAgMCEFya2Fuc2FzMQ8wDQYDVQQHDAZSb2dl
  cnMxFTATBgNVBAoMDFNpZ25hbDkgTGFiczEMMAoGA1UECwwDWE5BMR8wHQYDVQQD
  DBZTaWduYWw5IFJvb3QgQXV0aG9yaXR5MB4XDTIxMDMwMTA0MDMwNFoXDTQxMDIy
  NDA0MDMwNFowdzELMAkGA1UEBhMCVVMxETAPBgNVBAgMCEFya2Fuc2FzMQ8wDQYD
  VQQHDAZSb2dlcnMxFTATBgNVBAoMDFNpZ25hbDkgTGFiczEMMAoGA1UECwwDWE5B
  MR8wHQYDVQQDDBZTaWduYWw5IFJvb3QgQXV0aG9yaXR5MHYwEAYHKoZIzj0CAQYF
  K4EEACIDYgAE5w5BHLiaagf5eSNkQYuDIdyWe7ULLY2z2qAP1fKXM+RrSHQQb5x1
  Q9+IhQRhf7exw/pJS5Vs1R8IyQ3B8r6xz885w6+Fk6iyMAlFn979RU6V5lbxMRGG
  Vxq/CEL/iorVo2MwYTAdBgNVHQ4EFgQUYfO+q+KnTtIDK5OFXsVZ/D0ziiUwHwYD
  VR0jBBgwFoAUYfO+q+KnTtIDK5OFXsVZ/D0ziiUwDwYDVR0TAQH/BAUwAwEB/zAO
  BgNVHQ8BAf8EBAMCAYYwCgYIKoZIzj0EAwIDaQAwZgIxAJLOIPP9J1/mttvGdQtM
  Prnm+r+JzVu8vd0r2HxgwloEkElTr29S+DAAE8XlUpoXpQIxALEd+sYGr1qENJqr
  vHOvuo0diFSUxjvTjowus6kM6nZi1JR4rMycICsGgujg8zwVAw==
  -----END CERTIFICATE-----

cluster_ssh_pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ04V9hGUmgioucc86ru/tFNl4buDm1KA7lPokNFKkwC admin@bastion.rho.lab.signal9.gg"

cluster_dns_servers:
  - 172.18.60.10

cluster_ntp_sources: "{{ cluster_dns_servers }}"

cluster_sso:
  client_id: "{{ cluster_name }}-openshift"
  sso_url: https://sso.rho.lab.signal9.gg
  admin_realm: master
  role_source_client: hcp-hosted-clusters
  client_realm: "RHO"
  console_sso_label: "RHO"

nios_config:
  infoblox_host: rho-dns-a.rho.lab.signal9.gg
  dns_views:
    - Internal
    - External
  metallb_network_container: 172.18.72.0/22

platform_configs:
  kubevirt:
    ingress_base_domain: "apps.xna-foundation.{{ base_domain }}"
    cluster_sizes:
      sandbox:
        etcd_size: 8Gi
        worker_count: 3
        worker_cpu: 2
        worker_ram: 8Gi
        worker_disk: 64Gi
      small:
        etcd_size: 8Gi
        worker_count: 3
        worker_cpu: 8
        worker_ram: 32Gi
        worker_disk: 256Gi
      medium:
        etcd_size: 16Gi
        worker_count: 6
        worker_cpu: 8
        worker_ram: 32Gi
        worker_disk: 256Gi
      large:
        etcd_size: 32Gi
        worker_count: 9
        worker_cpu: 8
        worker_ram: 32Gi
        worker_disk: 256Gi

  agent:
    ingress_base_domain: "{{ base_domain }}"
    cluster_sizes:
      sandbox:
        etcd_size: 8Gi
        agent_count: 2
      small:
        etcd_size: 8Gi
        agent_count: 2
      medium:
        etcd_size: 16Gi
        agent_count: 3
      large:
        etcd_size: 32Gi
        agent_count: 5
