{{- range .Values.nodes -}}
{{- if .deployed | default false -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: {{ .name }}-creds
  namespace: {{ .namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: {{ .name }}-creds
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        username: '{{ "{{ .username }}" }}'
        password: '{{ "{{ .password }}" }}'
  data:
  - secretKey: username
    remoteRef:
      key: {{ .bmc.externalSecret.vaultName }}
      property: {{ .bmc.externalSecret.usernameKey }}
  - secretKey: password
    remoteRef:
      key: {{ .bmc.externalSecret.vaultName }}
      property: {{ .bmc.externalSecret.passwordKey }}
---
{{ end }}
{{ end }}
