{{- range .Values.nodes -}}
---
apiVersion: v1 
kind: Secret
metadata:
 name: {{ .name }}-net-config
 namespace: {{ .namespace }}
type: Opaque
stringData:
  nmstate: | 
    interfaces:
      - name: bond0
        type: bond
        state: up
        ipv4:
          enabled: false
          dhcp: false
        ipv6:
          enabled: false
        link-aggregation:
          mode: active-backup
          options:
            miimon: '100'
          port:
            {{ toYaml .network.bond0Interfaces | nindent 12 }}
      - name: bond1
        type: bond
        mtu: 9000
        state: up
        ipv4:
          enabled: false
          dhcp: false
        ipv6:
          enabled: false
        link-aggregation:
          mode: active-backup
          options:
            miimon: '100'
          port:
            {{ toYaml .network.bond1Interfaces | nindent 12 }}
      - name: bond1.{{ .network.mgmtVlan }}
        type: vlan
        state: up
        mtu: 9000
        vlan:
          id: {{ .network.mgmtVlan }}
          base-iface: bond1
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: {{ .network.mgmtIp }}
              prefix-length: 24
      - name: bond1.{{ .network.odfVlan }}
        type: vlan
        state: up
        mtu: 9000
        vlan:
          id: {{ .network.odfVlan }}
          base-iface: bond1
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: {{ .network.odfIp }}
              prefix-length: 24
    dns-resolver:
      config:
        server:
          {{ toYaml .network.dnsServers | nindent 10 }}
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: {{ .network.mgmtGateway }}
          next-hop-interface: rho-ocp
          table-id: 254
        - destination: 172.18.14.0/24
          next-hop-address: {{ .network.odfGateway }}
          next-hop-interface: odf
          table-id: 254
---
{{ end }}
