---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-password
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: keycloak-db-creds
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: keycloak-db-creds
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  namespace: keycloak
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: bastion.rho.lab.signal9.gg:8443/mirror/rhel8/postgresql-12@sha256:493358aa1f1f9aa0862fca14e27f972f73a6356b5032fe3b372432f0b6db880a
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: pg-data
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-creds
                  key: password
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-creds
                  key: username
            - name: POSTGRESQL_DATABASE
              value: keycloak
  volumeClaimTemplates:
  - metadata:
      name: pg-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: keycloak
spec:
  selector:
    app: postgresql-db
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
